### ISSUE TITLE
How to handle Token properly?

### ISSUE THREAD

**Issue by sonphnt** [juunas11/aspnetcore2aadauth#5]
Hi.

Your solution looks great!. I have a question that. Does this line handle all the stuff with token for you?
"GetAccessTokenAsync"

Such as get new token when it expires, or reuse the current token.

Thanks

**Comment by darewreck54** [comment]
I'm guessing if the token is expired AcquireTokenSilentAsync() will throw an exception and in the AdalTokenAcquisitionExceptionFilter it will try to reathenticate with a Challenge.  The user at that point needs to sign back in.

**Comment by juunas11** [comment]
@darewreck54 is right. ADAL will keep the refresh token in its cache. So if it finds a valid access token or refresh token in the cache, it will be able to get a new token "silently". Otherwise what he said will happen :) OnAuthorizationCodeReceived in Startup is what handles putting the tokens in cache after login.
